# Generated by Django 3.2.13 on 2022-06-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_auto_20220623_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='estado',
            field=models.CharField(max_length=30),
        ),
    ]
