# Generated by Django 3.2.13 on 2022-06-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_cursos_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='estado',
            new_name='camada',
        ),
    ]
